#ifndef __RV_MEMSAFE_H
#define __RV_MEMSAFE_H
#define __RV_gnu89

#define __RV_use_trie
/*===----------------------------------------------------------------------===//
//
//  This file is automatically generated for data structures.
//
//===----------------------------------------------------------------------===*/

#if !defined size_t
typedef unsigned long int size_t;
#endif

/*Status of memory blocks.*/
typedef enum
{
  __RV_invalid,
  __RV_function,
  __RV_global,
  __RV_static,
  __RV_heap,
  __RV_stack,
  __RV_library /* allocated in a library function */
} __RV_status;

/*Status node with auto-deallocation.*/
typedef struct
{
  __RV_status stat;
  size_t count;
} __RV_stat_node;

/*Addresses of predefined status nodes with auto-deallocation.
  Their lifetime is the entire run of the program.*/
extern __RV_stat_node *__RV_function_sa;
extern __RV_stat_node *__RV_global_sa;
extern __RV_stat_node *__RV_static_sa;
extern __RV_stat_node *__RV_library_sa;

/*Pointer address.*/
typedef const void * const * __RV_ptr_addr;

/*Function address.*/
typedef void (*__RV_func_addr)(void);

/*Split-order key.*/
typedef size_t __RV_so_key_t;

/*Pointer metadata.*/
typedef struct __RV_pmd
{
  const void *base;
  const void *bound;
  __RV_stat_node *snda;  /*status node address*/
#if defined __RV_use_trie
  unsigned char pmdflag;   /*0 - uninitialized/removed;
      1 - initialized/allocated; 2 - freeable temp pmd*/
#elif defined __RV_use_hashtable
  __RV_ptr_addr ptra;    /*pointer address*/
  struct __RV_pmd *next; /*for resolving hash collisions*/
#if defined __RV_use_ext_cas
  __RV_so_key_t so_key;  /*split-order key, i.e., the reverse of ptra field*/
#endif
#endif
} __RV_pmd;

#if defined __RV_use_trie
    #define __RV_pmd_init_val {0, 0, 0, 0}
#elif defined __RV_use_hashtable
  #if !defined __RV_use_ext_cas
    #define __RV_pmd_init_val {0, 0, 0, (__RV_ptr_addr)-1, 0}
  #else
    #define __RV_pmd_init_val {0, 0, 0, (__RV_ptr_addr)-1, 0, (size_t)-1}
  #endif
#endif

/*Pointer metadata in function pointer metadata.*/
typedef struct
{
  const void *base;
  const void *bound;
  __RV_stat_node *snda;  /*status node address*/
} __RV_fmd_pmd;

/*Function pointer metadata.*/
typedef struct __RV_fmd
{
  __RV_fmd_pmd *pmds;    /*pointer metadata*/
  unsigned char capacity;  /*number of pointer metadata*/
  __RV_func_addr func;   /*function address*/
  struct __RV_fmd *next; /*for resolving hash collisions*/
#if defined __RV_use_ext_cas
  unsigned t_idx;          /*thread index*/
  __RV_so_key_t so_key;  /*split-order key, i.e., the reverse of func field*/
#endif
} __RV_fmd;

/*Hash table for storing (function) pointer metadata.*/
typedef struct
{
  void **slots;    /*array  of slots*/
  size_t capacity; /*number of slots*/
  size_t size;     /*number of occupied slots*/
  size_t count;    /*number of inserted elements*/
} __RV_hashtbl;

/*Count of memory safety errors.*/
extern size_t __RV_error_count;

/*Print the runtime error count.*/
void __RV_print_error_count(void);
/*===----------------------------------------------------------------------===//
//
//  This file is automatically generated for metadata.
//
//===----------------------------------------------------------------------===*/

/*===----------------------------- utility --------------------------------===*/
inline
static const void *__RV_min_ptr(const void *ptr1, const void *ptr2)
{
  return ((ptr1 < ptr2) ? ptr1 : ptr2);
}
inline
static const void *__RV_max_ptr(const void *ptr1, const void *ptr2)
{
  return ((ptr1 > ptr2) ? ptr1 : ptr2);
}
/*===----------------------------- stat_node ------------------------------===*/
__RV_stat_node *__RV_stat_node_create(__RV_status stat, size_t count);
unsigned          __RV_stat_node_dec(__RV_stat_node *snda);
/*===----------------------------- pmd ------------------------------------===*/
__RV_pmd       *__RV_pmd_create(__RV_ptr_addr ptra, __RV_stat_node *snda,
                        __RV_status stat, const void *base, const void *bound);
void              __RV_pmd_free_null_ptr(__RV_pmd *pmd);
const void       *__RV_pmd_get_base(const __RV_pmd *pmd);
const void       *__RV_pmd_get_bound(const __RV_pmd *pmd);
__RV_stat_node *__RV_pmd_get_snda(const __RV_pmd *pmd);
__RV_status     __RV_pmd_get_stat(const __RV_pmd *pmd);
void              __RV_pmd_print(const __RV_pmd *pmd);
__RV_pmd       *__RV_pmd_set(__RV_pmd *pmd, __RV_stat_node *snda,
                        __RV_status stat, const void *base, const void *bound);
void             *__RV_pmd_set_ret(__RV_pmd *pmd, __RV_stat_node *snda,
                        __RV_status stat, const void *base, const void *bound, const void *ret);
void              __RV_pmd_set_null(__RV_pmd *pmd);
__RV_pmd       *__RV_pmd_cp_pmd(__RV_pmd *pmd, const __RV_pmd *pmd2);
void             *__RV_pmd_cp_pmd_ret(__RV_pmd *pmd, const __RV_pmd *pmd2, const void *ret);
__RV_pmd       *__RV_pmd_cp_fmd_pmd(__RV_pmd *pmd, const __RV_fmd_pmd *fpmd);
/*===----------------------------- fmd_pmd --------------------------------===*/
const void       *__RV_fmd_pmd_get_base(const __RV_fmd_pmd *fpmd);
const void       *__RV_fmd_pmd_get_bound(const __RV_fmd_pmd *fpmd);
/*===----------------------------------------------------------------------===//
//
//  This file is automatically generated for the functions related to
//  the algorithm for the dynamic analysis of memory safety.
//
//===----------------------------------------------------------------------===*/

/*===----------------------------- utilities ------------------------------===*/
int __RV_sstrlen(const char *str);
/*===----------------------------- pmd_tbl --------------------------------===*/
__RV_pmd *__RV_pmd_tbl_create(__RV_ptr_addr ptra);
__RV_pmd *__RV_pmd_tbl_lookup(__RV_ptr_addr ptra);
void        __RV_pmd_tbl_print(__RV_ptr_addr ptra, const char *ptr_name);
__RV_pmd *__RV_pmd_tbl_update_sa(__RV_ptr_addr ptra, __RV_stat_node *snda,
                         const void *base, const void *bound);
void       *__RV_pmd_tbl_update_sa_ret(__RV_ptr_addr ptra, __RV_stat_node *snda,
                         const void *base, const void *bound, const void *ret);
__RV_pmd *__RV_pmd_tbl_update_pmd(__RV_ptr_addr ptra, const __RV_pmd *pmd);
void       *__RV_pmd_tbl_update_pmd_ret(__RV_ptr_addr ptra, const __RV_pmd *pmd,
                         const void *ret);
__RV_pmd *__RV_pmd_tbl_update_fpmd(__RV_ptr_addr ptra, const __RV_fmd_pmd *fpmd);
__RV_pmd *__RV_pmd_tbl_update_ptr(__RV_ptr_addr ptra, __RV_ptr_addr ptra1);
void       *__RV_pmd_tbl_update_ptr_ret(__RV_ptr_addr ptra, __RV_ptr_addr ptra1,
                         const void *ret);
void        __RV_pmd_tbl_remove(__RV_ptr_addr ptra);
void        __RV_pmd_tbl_remove_pa(__RV_ptr_addr array, size_t size);
void        __RV_pmd_var_remove_pa(__RV_pmd *array, size_t size);

__RV_pmd *__RV_pmd_tbl_update_argv(int argc, char ***argv_addr, char * const argv[]);
__RV_pmd *__RV_pmd_var_update_argv(int argc, __RV_pmd *argv_pmd, char * const argv[]);
void        __RV_pmd_tbl_remove_argv(int argc, char ***argv_addr, char * const argv[]);
void        __RV_pmd_var_remove_argv(int argc, __RV_pmd *argv_pmd, char * const argv[]);
__RV_pmd *__RV_pmd_tbl_update_envp(char ***envp_addr, char **envp);
__RV_pmd *__RV_pmd_var_update_envp(__RV_pmd *envp_pmd, char **envp);
void        __RV_pmd_tbl_remove_envp(char ***envp_addr, char **envp);
void        __RV_pmd_var_remove_envp(__RV_pmd *envp_pmd, char **envp);
/*===----------------------------- fmd_tbl --------------------------------===*/
__RV_fmd     *__RV_fmd_tbl_create(__RV_func_addr func, unsigned char capacity);
__RV_fmd_pmd *__RV_fmd_tbl_lookup_fpmd(__RV_func_addr func, unsigned char i);
void            __RV_fmd_tbl_print(__RV_func_addr func, unsigned char i,
                             const char *func_name);
__RV_fmd     *__RV_fmd_tbl_update_pmd(__RV_func_addr func, unsigned char i,
                             const __RV_pmd *pmd);
void            __RV_fmd_tbl_remove(__RV_func_addr func);
/*===----------------------------- check ----------------------------------===*/
void *__RV_check_dpv(const __RV_pmd *pmd,
        const void *ptr, size_t size,
        const char *file_name, const char *func_name,
        unsigned line, unsigned column, const char *ptr_name);
long __RV_check_dpv_ss(const __RV_pmd *pmd,
        const void *ptr, long subscript, size_t size,
        const char *file_name, const char *func_name,
        unsigned line, unsigned column, const char *ptr_name);
void *__RV_check_dpfv(const __RV_pmd *pmd, const void *ptr,
        const char *file_name, const char *func_name,
        unsigned line, unsigned column, const char *ptr_name);
void *__RV_check_dpc(const void *base, const void *bound,
        const void *ptr, size_t size,
        const char *file_name, const char *func_name,
        unsigned line, unsigned column, const char *ptr_name);
long __RV_check_dpc_ss(const void *base, const void *bound,
        const void *ptr, long subscript, size_t size,
        const char *file_name, const char *func_name,
        unsigned line, unsigned column, const char *ptr_name);
void *__RV_check_dpfc(const void *base, const void *bound, const void *ptr,
        const char *file_name, const char *func_name,
        unsigned line, unsigned column, const char *ptr_name);
/*===----------------------------- bits/getopt_core -----------------------===*/
#include <getopt.h>

 int _RV_getopt(__RV_pmd *argv_pmd, __RV_pmd *options_pmd,
        int argc, char *const *argv, const char *options,
        const char *file_name, const char *func_name,
        unsigned a_line, unsigned a_col, const char *a_name,
        unsigned o_line, unsigned o_col, const char *o_name);
/*===----------------------------- math.h ---------------------------------===*/
#include <math.h>

 double _RV_frexp(__RV_pmd *exponent_pmd,
        double x, int *exponent,
        const char *file_name, const char *func_name,
        unsigned e_line, unsigned e_col, const char *e_name);

 double _RV_modf(__RV_pmd *integer_pmd,
        double x, double *integer,
        const char *file_name, const char *func_name,
        unsigned i_line, unsigned i_col, const char *i_name);
/*===----------------------------- stdio.h --------------------------------===*/
#include <stdio.h>

 int _RV__IO_getc(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV__IO_putc(__RV_pmd *fp_pmd,
        int ch, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 void _RV_clearerr(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_fclose(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

#if !defined _POSIX_C_SOURCE
 int _RV_fdopen(
        __RV_pmd *mode_pmd,
        int fd, const char *mode,
        const char *file_name, const char *func_name,
        unsigned m_line, unsigned m_col, const char *m_name);
#else
 FILE *_RV_fdopen(__RV_pmd *ret_pmd,
        __RV_pmd *mode_pmd,
        int fd, const char *mode,
        const char *file_name, const char *func_name,
        unsigned m_line, unsigned m_col, const char *m_name);
#endif

 int _RV_feof(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_ferror(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_fflush(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_fgetc(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_fgetpos(__RV_pmd *fp_pmd, __RV_pmd *pos_pmd,
        FILE *fp, fpos_t *pos,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 char *_RV_fgets(__RV_pmd *ret_pmd,
        __RV_pmd *str_pmd, __RV_pmd *fp_pmd,
        char *str, int n, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_fileno(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 FILE *_RV_fopen(__RV_pmd *ret_pmd,
        __RV_pmd *filename_pmd, __RV_pmd *mode_pmd,
        const char *filename, const char *mode,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned m_line, unsigned m_col, const char *m_name);

 int _RV_fputc(__RV_pmd *fp_pmd,
        int ch, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_fputs(__RV_pmd *str_pmd, __RV_pmd *fp_pmd,
        const char *str, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 size_t _RV_fread(__RV_pmd *ptr_pmd, __RV_pmd *fp_pmd,
        void *ptr, size_t size, size_t nmemb, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 FILE *_RV_freopen(__RV_pmd *ret_pmd,
        __RV_pmd *filename_pmd, __RV_pmd *mode_pmd, __RV_pmd *fp_pmd,
        const char *filename, const char *mode, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned m_line, unsigned m_col, const char *m_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 int _RV_fseek(__RV_pmd *fp_pmd,
        FILE *fp, long int offset, int whence,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_fsetpos(__RV_pmd *fp_pmd, __RV_pmd *pos_pmd,
        FILE *fp, const fpos_t *pos,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 long int _RV_ftell(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 size_t _RV_fwrite(__RV_pmd *ptr_pmd, __RV_pmd *fp_pmd,
        const void *ptr, size_t size, size_t nmemb, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_getc(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

#if !defined __USE_ISOC11 || (defined __cplusplus && __cplusplus <= 201103L)
 char *_RV_gets(__RV_pmd *ret_pmd,
        __RV_pmd *str_pmd,
        char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);
#else
 int _RV_gets(
        __RV_pmd *str_pmd,
        char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);
#endif

#if _POSIX_C_SOURCE >= 2 || /* Glibc <= 2.19: */ defined _BSD_SOURCE || defined _SVID_SOURCE
 int _RV_pclose(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);
#endif

 void _RV_perror(__RV_pmd *str_pmd,
        const char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);

#if _POSIX_C_SOURCE >= 2 || /* Glibc <= 2.19: */ defined _BSD_SOURCE || defined _SVID_SOURCE
 FILE *_RV_popen(__RV_pmd *ret_pmd,
        __RV_pmd *filename_pmd, __RV_pmd *mode_pmd,
        const char *filename, const char *mode,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned m_line, unsigned m_col, const char *m_name);
#endif

 int _RV_putc(__RV_pmd *fp_pmd,
        int ch, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_puts(__RV_pmd *str_pmd,
        const char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);

 int _RV_remove(__RV_pmd *filename_pmd,
        const char *filename,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_rename(__RV_pmd *old_pmd, __RV_pmd *new_pmd,
        const char *old_filename, const char *new_filename,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned n_line, unsigned n_col, const char *n_name);

 void _RV_rewind(__RV_pmd *fp_pmd,
        FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 void _RV_setbuf(__RV_pmd *fp_pmd, __RV_pmd *buffer_pmd,
        FILE *fp, char *buffer,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned b_line, unsigned b_col, const char *b_name);

 int _RV_setvbuf(__RV_pmd *fp_pmd, __RV_pmd *buffer_pmd,
        FILE *fp, char *buffer, int mode, size_t size,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned b_line, unsigned b_col, const char *b_name);

 FILE *_RV_tmpfile(__RV_pmd *ret_pmd);

#if defined __GNUC__
 char *_RV_tmpnam(__RV_pmd *ret_pmd,
        __RV_pmd *str_pmd,
        char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);
#endif

 int _RV_ungetc(__RV_pmd *fp_pmd,
        int ch, FILE *fp,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

#include <stdarg.h>

int vasprintf(char **strp, const char *fmt, va_list ap);

 int _RV_vasprintf(
        __RV_pmd *strp_pmd, __RV_pmd *fmt_pmd, __RV_pmd *ap_pmd,
        char **strp, const char *fmt, va_list ap,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned a_line, unsigned a_col, const char *a_name);

 int _RV_vfprintf(
        __RV_pmd *fp_pmd, __RV_pmd *format_pmd, __RV_pmd *arg_pmd,
        FILE *fp, const char *format, va_list arg,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned r_line, unsigned r_col, const char *r_name,
        unsigned a_line, unsigned a_col, const char *a_name);

 int _RV_vprintf(__RV_pmd *format_pmd, __RV_pmd *arg_pmd,
        const char *format, va_list arg,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned a_line, unsigned a_col, const char *a_name);

 int _RV_vsprintf(
        __RV_pmd *str_pmd, __RV_pmd *format_pmd, __RV_pmd *arg_pmd,
        char *str, const char *format, va_list arg,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned a_line, unsigned a_col, const char *a_name);
/*===----------------------------- stdlib.h -------------------------------===*/
#include <stdlib.h>

 int _RV_atexit(__RV_pmd *func_pmd,
        void (*func)(void),
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 double _RV_atof(__RV_pmd *str_pmd,
        const char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);

 int _RV_atoi(__RV_pmd *str_pmd,
        const char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);

 long int _RV_atol(__RV_pmd *str_pmd,
        const char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);

 void *_RV_bsearch(__RV_pmd *ret_pmd,
        __RV_pmd *key_pmd, __RV_pmd *base_pmd, __RV_pmd *compar_pmd,
        const void *key, const void *base, size_t nmemb, size_t size, __compar_fn_t compar,
        const char *file_name, const char *func_name,
        unsigned k_line, unsigned k_col, const char *k_name,
        unsigned b_line, unsigned b_col, const char *b_name,
        unsigned c_line, unsigned c_col, const char *c_name);

 void *_RV_calloc(__RV_pmd *ret_pmd,
        size_t n, size_t size);

 void _RV_free(__RV_pmd *ptr_pmd,
        void *ptr,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 char *_RV_getenv(__RV_pmd *ret_pmd, __RV_pmd *name_pmd,
        const char *name,
        const char *file_name, const char *func_name,
        unsigned n_line, unsigned n_col, const char *n_name);

 void *_RV_malloc(__RV_pmd *ret_pmd,
        size_t size);

 int _RV_mblen(__RV_pmd *str_pmd,
        const char *str, size_t n,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);

 size_t _RV_mbstowcs(__RV_pmd *pwcs_pmd, __RV_pmd *str_pmd,
        wchar_t *pwcs, const char *str, size_t n,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name,
        unsigned s_line, unsigned s_col, const char *s_name);

 int _RV_mbtowc(__RV_pmd *pwc_pmd, __RV_pmd *str_pmd,
        wchar_t *pwc, const char *str, size_t n,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name,
        unsigned s_line, unsigned s_col, const char *s_name);



#ifdef __USE_GNU
 char *_RV_ptsname(__RV_pmd *ret_pmd, int fd);
#endif

 int _RV_putenv(__RV_pmd *str_pmd, char *__string,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);

 void _RV_qsort(
        __RV_pmd *base_pmd, __RV_pmd *compar_pmd,
        void *base, size_t num, size_t size, __compar_fn_t compar,
        const char *file_name, const char *func_name,
        unsigned b_line, unsigned b_col, const char *b_name,
        unsigned c_line, unsigned c_col, const char *c_name);

 void *_RV_realloc(__RV_pmd *ret_pmd, __RV_pmd *ptr_pmd,
        void *ptr, size_t newsize,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 double _RV_strtod(__RV_pmd *str_pmd, __RV_pmd *endptr_pmd,
        const char *str, char **endptr,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name,
        unsigned e_line, unsigned e_col, const char *e_name);

 long int _RV_strtol(__RV_pmd *str_pmd, __RV_pmd *endptr_pmd,
        const char *str, char **endptr, int base,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name,
        unsigned e_line, unsigned e_col, const char *e_name);

 unsigned long int _RV_strtoul(
        __RV_pmd *str_pmd, __RV_pmd *endptr_pmd,
        const char *str, char **endptr, int base,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name,
        unsigned e_line, unsigned e_col, const char *e_name);

 int _RV_system(__RV_pmd *str_pmd,
        const char *str,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);

 size_t _RV_wcstombs(__RV_pmd *str_pmd, __RV_pmd *pwcs_pmd,
        char *str, const wchar_t *pwcs, size_t n,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 int _RV_wctomb(__RV_pmd *str_pmd,
        char *str, wchar_t wchar,
        const char *file_name, const char *func_name,
        unsigned s_line, unsigned s_col, const char *s_name);
/*===----------------------------- string.h -------------------------------===*/
#include <string.h>

 void _RV_bcopy(__RV_pmd *src_pmd, __RV_pmd *dest_pmd,
                       const void *src, void *dest, size_t n,
                       const char *file_name, const char *func_name,
                       unsigned s_line, unsigned s_col, const char *s_name,
                       unsigned d_line, unsigned d_col, const char *d_name);

 void _RV_bzero(__RV_pmd *s_pmd,
                       void *s, size_t n,
                       const char *file_name, const char *func_name,
                       unsigned s_line, unsigned s_col, const char *s_name);

#if defined __USE_MISC || defined __USE_XOPEN
 void *_RV_memccpy(__RV_pmd *ret_pmd,
                          __RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                          void *dest, const void *src, int c, size_t n,
                          const char *file_name, const char *func_name,
                          unsigned d_line, unsigned d_col, const char *d_name,
                          unsigned s_line, unsigned s_col, const char *s_name);
#else
 int _RV_memccpy(__RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                          void *dest, const void *src, int c, size_t n,
                          const char *file_name, const char *func_name,
                          unsigned d_line, unsigned d_col, const char *d_name,
                          unsigned s_line, unsigned s_col, const char *s_name);
#endif

 void *_RV_memchr(__RV_pmd *ret_pmd, __RV_pmd *src_pmd,
                         const void *src, int c, size_t n,
                         const char *file_name, const char *func_name,
                         unsigned s_line, unsigned s_col, const char *s_name);

 int _RV_memcmp(__RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
                       const void *str1, const void *str2, size_t n,
                       const char *file_name, const char *func_name,
                       unsigned s1_line, unsigned s1_col, const char *s1_name,
                       unsigned s2_line, unsigned s2_col, const char *s2_name);

 void *_RV_memcpy(__RV_pmd *ret_pmd,
                         __RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                         void *dest, const void *src, size_t n,
                         const char *file_name, const char *func_name,
                         unsigned d_line, unsigned d_col, const char *d_name,
                         unsigned s_line, unsigned s_col, const char *s_name);

 void *_RV_memmove(__RV_pmd *ret_pmd,
                          __RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                          void *dest, const void *src, size_t n,
                          const char *file_name, const char *func_name,
                          unsigned d_line, unsigned d_col, const char *d_name,
                          unsigned s_line, unsigned s_col,  const char *s_name);

 void *_RV_memset(__RV_pmd *ret_pmd, __RV_pmd *str_pmd,
                         void *str, int c, size_t n,
                         const char *file_name, const char *func_name,
                         unsigned s_line, unsigned s_col, const char *s_name);

#ifdef __USE_MISC
 int _RV_strcasecmp(__RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
        const char *str1, const char *str2,
        const char *file_name, const char *func_name,
        unsigned s1_line, unsigned s1_col, const char *s1_name,
        unsigned s2_line, unsigned s2_col, const char *s2_name);
#endif

 char *_RV_strcat(__RV_pmd *ret_pmd,
                         __RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                         char *dest, const char *src,
                         const char *file_name, const char *func_name,
                         unsigned d_line, unsigned d_col, const char *d_name,
                         unsigned s_line, unsigned s_col, const char *s_name);

 char *_RV_strchr(__RV_pmd *ret_pmd, __RV_pmd *src_pmd,
                         const char *src, int c,
                         const char *file_name, const char *func_name,
                         unsigned s_line, unsigned s_col, const char *s_name);

 int _RV_strcmp(__RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
                       const char *str1, const char *str2,
                       const char *file_name, const char *func_name,
                       unsigned s1_line, unsigned s1_col, const char *s1_name,
                       unsigned s2_line, unsigned s2_col, const char *s2_name);

 int _RV_strcoll(__RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
                        const char *str1, const char *str2,
                        const char *file_name, const char *func_name,
                        unsigned s1_line, unsigned s1_col, const char *s1_name,
                        unsigned s2_line, unsigned s2_col, const char *s2_name);

 char *_RV_strcpy(__RV_pmd *ret_pmd,
                         __RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                         char *dest, const char *src,
                         const char *file_name, const char *func_name,
                         unsigned d_line, unsigned d_col, const char *d_name,
                         unsigned s_line, unsigned s_col, const char *s_name);

 size_t _RV_strcspn(__RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
                   const char *str1, const char *str2,
                   const char *file_name, const char *func_name,
                   unsigned s1_line, unsigned s1_col, const char *s1_name,
                   unsigned s2_line, unsigned s2_col, const char *s2_name);

#if _XOPEN_SOURCE >= 500 || /* Since glibc 2.12: */ _POSIX_C_SOURCE >= 200809L || \
    /* Glibc <= 2.19: */ defined _BSD_SOURCE || defined _SVID_SOURCE
 char *_RV_strdup(__RV_pmd *ret_pmd, __RV_pmd *str_pmd,
                         const char *str,
                         const char *file_name, const char *func_name,
                         unsigned s_line, unsigned s_col, const char *s_name);
#endif

 char *_RV_strerror(__RV_pmd *ret_pmd,
                           int errnum);

 size_t _RV_strlen(__RV_pmd *str_pmd,
                          const char *str,
                          const char *file_name, const char *func_name,
                          unsigned s_line, unsigned s_col, const char *s_name);

#ifdef __USE_MISC
 int _RV_strncasecmp(__RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
        const char *str1, const char *str2, size_t n,
        const char *file_name, const char *func_name,
        unsigned s1_line, unsigned s1_col, const char *s1_name,
        unsigned s2_line, unsigned s2_col, const char *s2_name);
#endif

 char *_RV_strncat(__RV_pmd *ret_pmd,
                          __RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                          char *dest, const char *src, size_t n,
                          const char *file_name, const char *func_name,
                          unsigned d_line, unsigned d_col, const char *d_name,
                          unsigned s_line, unsigned s_col, const char *s_name);

 int _RV_strncmp(__RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
                        const char *str1, const char *str2, size_t n,
                        const char *file_name, const char *func_name,
                        unsigned s1_line, unsigned s1_col, const char *s1_name,
                        unsigned s2_line, unsigned s2_col, const char *s2_name);

 char *_RV_strncpy(__RV_pmd *ret_pmd,
                          __RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                          char *dest, const char *src, size_t n,
                          const char *file_name, const char *func_name,
                          unsigned d_line, unsigned d_col, const char *d_name,
                          unsigned s_line, unsigned s_col, const char *s_name);

 char *_RV_strpbrk(__RV_pmd *ret_pmd,
            __RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
            const char *str1, const char *str2,
            const char *file_name, const char *func_name,
            unsigned s1_line, unsigned s1_col, const char *s1_name,
            unsigned s2_line, unsigned s2_col, const char *s2_name);

 char *_RV_strrchr(__RV_pmd *ret_pmd, __RV_pmd *str_pmd,
                          const char *str, int c,
                          const char *file_name, const char *func_name,
                          unsigned s_line, unsigned s_col, const char *s_name);

#ifdef __USE_XOPEN2K8
 char *_RV_strsignal(__RV_pmd *ret_pmd, int __sig);
#endif

 size_t _RV_strspn(__RV_pmd *str1_pmd, __RV_pmd *str2_pmd,
                          const char *str1, const char *str2,
                          const char *file_name, const char *func_name,
                          unsigned s_line, unsigned s_col, const char *s_name,
                          unsigned t_line, unsigned t_col, const char *t_name);

 char *_RV_strstr(__RV_pmd *ret_pmd,
                         __RV_pmd *haystack_pmd, __RV_pmd *needle_pmd,
                         const char *haystack, const char *needle,
                         const char *file_name, const char *func_name,
                         unsigned h_line, unsigned h_col, const char *h_name,
                         unsigned n_line, unsigned n_col, const char *n_name);

 char *_RV_strtok(__RV_pmd *ret_pmd,
                         __RV_pmd *str_pmd, __RV_pmd *delim_pmd,
                         char *str, const char *delim,
                         const char *file_name, const char *func_name,
                         unsigned s_line, unsigned s_col, const char *s_name,
                         unsigned d_line, unsigned d_col, const char *d_name);

 size_t _RV_strxfrm(__RV_pmd *dest_pmd, __RV_pmd *src_pmd,
                           char *dest, const char *src, size_t n,
                           const char *file_name, const char *func_name,
                           unsigned d_line, unsigned d_col, const char *d_name,
                           unsigned s_line, unsigned s_col, const char *s_name);
/*===----------------------------- sys/select.h ---------------------------===*/
#include <sys/select.h>

 int _RV_select(__RV_pmd *readfds_pmd, __RV_pmd *writefds_pmd,
        __RV_pmd *exceptfds_pmd, __RV_pmd *timeout_pmd,
        int __nfds, fd_set *__restrict __readfds, fd_set *__restrict __writefds,
        fd_set *__restrict __exceptfds, struct timeval *__restrict __timeout,
        const char *file_name, const char *func_name,
        unsigned r_line, unsigned r_col, const char *r_name,
        unsigned w_line, unsigned w_col, const char *w_name,
        unsigned e_line, unsigned e_col, const char *e_name,
        unsigned t_line, unsigned t_col, const char *t_name);
/*===----------------------------- unistd.h -------------------------------===*/
#include <unistd.h>

 int _RV_access(__RV_pmd *name_pmd,
        const char *__name, int __type,
        const char *file_name, const char *func_name,
        unsigned n_line, unsigned n_col, const char *n_name);

 int _RV_chdir(__RV_pmd *path_pmd, const char *__path,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 int _RV_execv(__RV_pmd *path_pmd, __RV_pmd *argv_pmd,
        const char *__path, char *const __argv[],
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name,
        unsigned a_line, unsigned a_col, const char *a_name);

 int _RV_execvp(__RV_pmd *file_pmd, __RV_pmd *argv_pmd,
        const char *__file, char *const __argv[],
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned a_line, unsigned a_col, const char *a_name);

 char *_RV_getcwd(__RV_pmd *ret_pmd, __RV_pmd *buf_pmd,
        char *buf, size_t size,
        const char *file_name, const char *func_name,
        unsigned b_line, unsigned b_col, const char *b_name);

 int _RV_link(__RV_pmd *from_pmd, __RV_pmd *to_pmd,
        const char *__from, const char *__to,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name,
        unsigned t_line, unsigned t_col, const char *t_name);

 int _RV_pipe(__RV_pmd *pipedes_pmd, int __pipedes[2],
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 ssize_t _RV_read(__RV_pmd *buf_pmd,
        int fd, void *buf, size_t nbytes,
        const char *file_name, const char *func_name,
        unsigned b_line, unsigned b_col, const char *b_name);

 int _RV_rmdir(__RV_pmd *path_pmd, const char *__path,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 int _RV_truncate(__RV_pmd *file_pmd,
        const char *__file, __off_t __length,
        const char *file_name, const char *func_name,
        unsigned f_line, unsigned f_col, const char *f_name);

 int _RV_unlink(__RV_pmd *path_pmd,
        const char *path,
        const char *file_name, const char *func_name,
        unsigned p_line, unsigned p_col, const char *p_name);

 ssize_t _RV_write(__RV_pmd *buf_pmd,
        int fd, const void *buf, size_t nbytes,
        const char *file_name, const char *func_name,
        unsigned b_line, unsigned b_col, const char *b_name);

 void __RV_unistd_init_code(void);

 void __RV_unistd_clear_code(void);
/*===----------------------------- call by ptr ----------------------------===*/

 void __RV_call_wrapper_by_ptr(void (*fp)(void), ...);

 int __RV_has_wrapper(void (*fp)(void));

void __RV_global_init_code(void);

void __RV_global_clear_code(void);


#endif
